name: PR 


on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

env: 
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0


jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
      web: ${{ steps.filter.outputs.web }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - 'src/**'
              - 'examples/**'
              - 'tests/**'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'Dockerfile'
              - 'Makefile'
            web:
              - 'matchbox_web/**'

  build_and_test_rust:
    needs: detect_changes
    if: needs.detect_changes.outputs.rust == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Dependencies
        run: cargo vendor
      - name: Test
        run: make test
      - name: Style Check
        run: make format
      - name: Build matchbox
        run: make build_docker_matchbox_server

  build_and_test_web:
    needs: detect_changes
    if: needs.detect_changes.outputs.web == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: matchbox_web
    steps:
      - name: Check out
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: matchbox_web/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build
      
      - name: Build web components
        run: npm run build:webcomponents 