name: Publish to GitHub Pages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Login docker
        run: docker login https://ghcr.io -u wquintal -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
      - name: Dependency
        run: sudo apt-get install g++ make pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev && rustup component add rustfmt
      - name: Dependencies
        run: cargo vendor
      - name: Build docker matchbox
        run: make build_docker_matchbox_server
      - name: Publish docker matchbox
        run: make push_docker_matchbox_server
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # This is the standard token for GitHub API actions
        with:
          generate_release_notes: true